// Mocks generated by Mockito 5.4.5 from annotations
// in ecommerce_app/test/features/product/presentation/bloc_product_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ecommerce_app/core/error/failures.dart' as _i6;
import 'package:ecommerce_app/core/usecases/usecase.dart' as _i9;
import 'package:ecommerce_app/features/product/domain/entities/product.dart'
    as _i7;
import 'package:ecommerce_app/features/product/domain/repositories/product_repositories.dart'
    as _i2;
import 'package:ecommerce_app/features/product/domain/usecases/create_product_usecase.dart'
    as _i10;
import 'package:ecommerce_app/features/product/domain/usecases/delete_product_usecase.dart'
    as _i8;
import 'package:ecommerce_app/features/product/domain/usecases/update_product_usecase.dart'
    as _i4;
import 'package:ecommerce_app/features/product/domain/usecases/view_all_products_use_case.dart'
    as _i11;
import 'package:ecommerce_app/features/product/domain/usecases/view_product_usecase.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductRepository_0 extends _i1.SmartFake
    implements _i2.ProductRepository {
  _FakeProductRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UpdateProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductUsecase extends _i1.Mock
    implements _i4.UpdateProductUsecase {
  MockUpdateProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Product>> call(_i7.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [product],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>.value(
            _FakeEither_1<_i6.Failure, _i7.Product>(
          this,
          Invocation.method(
            #call,
            [product],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>);
}

/// A class which mocks [DeleteProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductUseCase extends _i1.Mock
    implements _i8.DeleteProductUseCase {
  MockDeleteProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(
          _i9.DeleteProductParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
            _FakeEither_1<_i6.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}

/// A class which mocks [CreateProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateProductUsecase extends _i1.Mock
    implements _i10.CreateProductUsecase {
  MockCreateProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Product>> execute(
          _i7.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [product],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>.value(
            _FakeEither_1<_i6.Failure, _i7.Product>(
          this,
          Invocation.method(
            #execute,
            [product],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Product>> call(_i7.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [product],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>.value(
            _FakeEither_1<_i6.Failure, _i7.Product>(
          this,
          Invocation.method(
            #call,
            [product],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>);
}

/// A class which mocks [ViewAllProductsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewAllProductsUsecase extends _i1.Mock
    implements _i11.ViewAllProductsUsecase {
  MockViewAllProductsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Product>>> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Product>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Product>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Product>>>);
}

/// A class which mocks [ViewProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewProductUsecase extends _i1.Mock
    implements _i12.ViewProductUsecase {
  MockViewProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Product?>> call(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [productId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Product?>>.value(
            _FakeEither_1<_i6.Failure, _i7.Product?>(
          this,
          Invocation.method(
            #call,
            [productId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Product?>>);
}
